### PR TITLE
AuditPolicyCsv for Issue #28

### PR DESCRIPTION
**Pull request by athaynes**
initial review

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/auditpolicydsc/29)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Reviewed 5 of 15 files at r2.
Review status: 5 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 92 at r3](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-K_poip2YHKojbh25O89:-K_poip2YHKojbh25O8A:b-thl057) ([raw file](https://github.com/powershell/auditpolicydsc/blob/7de50e335a9492835a8bc10f45a964453561bd1b/README.md#L92)):*
> ```Markdown
> #### Parameters
> 
> * **[String] CsvPath _(Key)_**: The path to the CSV file to apply to the node.
> ```

This should be a single instance resource: https://msdn.microsoft.com/en-us/powershell/dsc/singleinstance

---

*[DSCResources/AuditPolicyResourceHelper/AuditPolicyResourceHelper.psm1, line 139 at r3](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-K_pnk2SJI6MYcbnr9-R:-K_pnk2SJI6MYcbnr9-S:b-igj2r6) ([raw file](https://github.com/powershell/auditpolicydsc/blob/7de50e335a9492835a8bc10f45a964453561bd1b/DSCResources/AuditPolicyResourceHelper/AuditPolicyResourceHelper.psm1#L139)):*
> $return

This variable needs a more descriptive name. I would suggest $auditPolicyCommandResult
If you are trying to return here please add the return keyword like this `return $return`.

---

*[DSCResources/AuditPolicyResourceHelper/AuditPolicyResourceHelper.psm1, line 233 at r3](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-K_ppFRz1zoQA7XhWqlp:-K_ppFRz1zoQA7XhWqlq:b-9g8f67) ([raw file](https://github.com/powershell/auditpolicydsc/blob/7de50e335a9492835a8bc10f45a964453561bd1b/DSCResources/AuditPolicyResourceHelper/AuditPolicyResourceHelper.psm1#L233)):*
> ```PowerShell
>         Invoke-SecurityCmdlet -Action Import -Path .\test.csv
> #>
> function Invoke-SecurityCmdlet
> ```

This function is repeated in AuditPolicyCsv, and it doesn't seem to be used anywhere else.
You can take it out of the helper module.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29)*

**Comment by athaynes** [comment]
Review status: 4 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 92 at r3](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-K_poip2YHKojbh25O89:-KaHWd2olS6kpUceTJqg:b-26q6x5) ([raw file](https://github.com/powershell/auditpolicydsc/blob/7de50e335a9492835a8bc10f45a964453561bd1b/README.md#L92)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

This should be a single instance resource: https://msdn.microsoft.com/en-us/powershell/dsc/singleinstance
</blockquote></details>

I updated the readme and module to work as a single instance. Do you want me to add a test to validate the single instance works properly? 

---

*[DSCResources/AuditPolicyResourceHelper/AuditPolicyResourceHelper.psm1, line 139 at r3](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-K_pnk2SJI6MYcbnr9-R:-KaHWwwfy_pKRgUQlrVF:bb6un1j) ([raw file](https://github.com/powershell/auditpolicydsc/blob/7de50e335a9492835a8bc10f45a964453561bd1b/DSCResources/AuditPolicyResourceHelper/AuditPolicyResourceHelper.psm1#L139)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

> $return

This variable needs a more descriptive name. I would suggest $auditPolicyCommandResult
If you are trying to return here please add the return keyword like this `return $return`.
</blockquote></details>

Done

---

*[DSCResources/AuditPolicyResourceHelper/AuditPolicyResourceHelper.psm1, line 233 at r3](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-K_ppFRz1zoQA7XhWqlp:-KaHX1EWtK__yOitq0hO:bss4a2b) ([raw file](https://github.com/powershell/auditpolicydsc/blob/7de50e335a9492835a8bc10f45a964453561bd1b/DSCResources/AuditPolicyResourceHelper/AuditPolicyResourceHelper.psm1#L233)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

This function is repeated in AuditPolicyCsv, and it doesn't seem to be used anywhere else.
You can take it out of the helper module.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29)*

**Comment by athaynes** [comment]
I also updated all of the integration tests to use TestDrive instead of the working directory from Initialize-TestEnvironment.

**Comment by kwirkykat** [comment]
Reviewed 2 of 15 files at r2, 8 of 11 files at r4.
Review status: 14 of 17 files reviewed at latest revision, 7 unresolved discussions.

---

*[README.md, line 92 at r3](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-K_poip2YHKojbh25O89:-KamTftRONlAUappbnW5:bo9btxi) ([raw file](https://github.com/powershell/auditpolicydsc/blob/7de50e335a9492835a8bc10f45a964453561bd1b/README.md#L92)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

I updated the readme and module to work as a single instance. Do you want me to add a test to validate the single instance works properly? 
</blockquote></details>

It's a known template for a single-instance resource so you can add tests if you'd like, but I won't require it.

---

*[README.md, line 27 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamV2kkv13kZnhlvKAQ:-KamV2kkv13kZnhlvKAR:b4gqsig) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/README.md#L27)):*
> policy backup.

policy backup from a CSV file.

---

*[README.md, line 102 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamUrfppI3eLuyYCSUW:-KamUrfppI3eLuyYCSUX:b84lhbh) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/README.md#L102)):*
> auditpol backup

audit policy backup from a CSV file

---

*[README.md, line 109 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamUwlAsMFrWrmZYCSf:-KamUwlAsMFrWrmZYCSg:bby42zl) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/README.md#L109)):*
> module

resource

---

*[DSCResources/MSFT_AuditPolicyCsv/MSFT_AuditPolicyCsv.psm1, line 159 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamStfNiWCSkUCwXjc3:-KamStfNiWCSkUCwXjc4:b-9qbjnt) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/DSCResources/MSFT_AuditPolicyCsv/MSFT_AuditPolicyCsv.psm1#L159)):*
> if ($inDesiredState)
> {
>     return $true
> }
> else
> {
>             return $false
> }

Just `return $inDesiredState`

---

*[DSCResources/MSFT_AuditPolicyCsv/MSFT_AuditPolicyCsv.psm1, line 261 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamTY9XMcpz981ct8Nx:-KamTY9XMcpz981ct8Ny:b47hzgn) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/DSCResources/MSFT_AuditPolicyCsv/MSFT_AuditPolicyCsv.psm1#L261)):*
> Write-Error $error[0]

Is this needed?

---

*[Examples/Sample_AuditPolicyCsv.ps1, line 2 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamTvveRSl2KhYeTLPp:-KamTvveRSl2KhYeTLPq:bodaj79) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/Examples/Sample_AuditPolicyCsv.ps1#L2)):*
> in the csv to the localhost.

in the CSV located at C:\data\AuditPolBackup.csv to the localhost.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29)*

**Comment by athaynes** [comment]
Review status: 14 of 17 files reviewed at latest revision, 7 unresolved discussions.

---

*[README.md, line 27 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamV2kkv13kZnhlvKAQ:-KapNWl-0mWXFN0PGDDY:b-896fix) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/README.md#L27)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

> policy backup.

policy backup from a CSV file.
</blockquote></details>

Done.

---

*[README.md, line 102 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamUrfppI3eLuyYCSUW:-KapNjas1ppF0b_52-az:b-896fix) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/README.md#L102)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

> auditpol backup

audit policy backup from a CSV file
</blockquote></details>

Done.

---

*[README.md, line 109 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamUwlAsMFrWrmZYCSf:-KapNj6W5oO0txVLdJFu:b-896fix) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/README.md#L109)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

> module

resource
</blockquote></details>

Done.

---

*[DSCResources/MSFT_AuditPolicyCsv/MSFT_AuditPolicyCsv.psm1, line 159 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamStfNiWCSkUCwXjc3:-KapOGX54pMVjAkTvIne:b-896fix) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/DSCResources/MSFT_AuditPolicyCsv/MSFT_AuditPolicyCsv.psm1#L159)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

> if ($inDesiredState)
> {
>     return $true
> }
> else
> {
>             return $false
> }

Just `return $inDesiredState`
</blockquote></details>

Done.

---

*[DSCResources/MSFT_AuditPolicyCsv/MSFT_AuditPolicyCsv.psm1, line 261 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamTY9XMcpz981ct8Nx:-KapOyG07VZfs0aqDko2:b-7qou8n) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/DSCResources/MSFT_AuditPolicyCsv/MSFT_AuditPolicyCsv.psm1#L261)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

> Write-Error $error[0]

Is this needed?
</blockquote></details>

Since we are creating a temp file, if it is not being cleaned up I wanted to inform the user as to why. The temp file is created each time the resource runs and I didn't want to create a bunch of junk on their computers and let it go unnoticed. 

---

*[Examples/Sample_AuditPolicyCsv.ps1, line 2 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamTvveRSl2KhYeTLPp:-KapQDImj2mQpBtmmWVn:b-896fix) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/Examples/Sample_AuditPolicyCsv.ps1#L2)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

> in the csv to the localhost.

in the CSV located at C:\data\AuditPolBackup.csv to the localhost.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29)*

**Comment by kwirkykat** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r5.
Review status: 15 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_AuditPolicyCsv/MSFT_AuditPolicyCsv.psm1, line 261 at r4](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-KamTY9XMcpz981ct8Nx:-Kas9nP19wbvSSDP_D2P:b32w1t) ([raw file](https://github.com/powershell/auditpolicydsc/blob/ac042550259d3836f8ec3220e108c4170698aa8b/DSCResources/MSFT_AuditPolicyCsv/MSFT_AuditPolicyCsv.psm1#L261)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

Since we are creating a temp file, if it is not being cleaned up I wanted to inform the user as to why. The temp file is created each time the resource runs and I didn't want to create a bunch of junk on their computers and let it go unnoticed. 
</blockquote></details>

Ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/auditpolicydsc/29#-:-Kas9xkfWuL_iuSLHNBz:bnfp4nl)*

**Pull request merged**
