### PR TITLE
auditpol CSV output is returned as an object

### LINKED ISSUE #36: auditpol csv output should be returned as an object
The Invoke-AuditPol helper function calls auditpol.exe with the /r switch which returns a CSV. Those strings are manually split and processed, when the output should be passed to ConvertFrom-Csv, so that the resources can process objects instead of strings.

### LINKED ISSUE #39: AuditPolicySubcategory Ensure default value missing in Test-TargetResource
AuditPolicySubcategory "NOT_ASSIGNED: Ensure 'Audit PNP Activity' is set to 'Success'"
{
 	Name = 'Plug and Play Events'
 	AuditFlag = 'Success'

}
Will not result in a desired state. It keeps testing the result. 
The following will work though. 

AuditPolicySubcategory "NOT_ASSIGNED: Ensure 'Audit PNP Activity' is set to 'Success'"
{
 	Name = 'Plug and Play Events'
 	AuditFlag = 'Success'
 	Ensure = 'Present'
}

The documentation state the default value for Ensure is present. It is set for the Set-TargetResource  but not the Test-TargetResourse ensure parameter.

### PR DESCRIPTION
**Pull request by athaynes**
Addresses Issue 36 and 39

Fixes #36 
Fixes #39 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/auditpolicydsc/37)

### CODE REVIEW

**Comment by johlju** [comment]
@athaynes If I review this one, do you have time to work on this?

**Comment by athaynes** [comment]
@johlju I totally forgot about this. Yeah, I'll get this done this weekend if you have a chance to review it.

**Comment by johlju** [comment]
Reviewed 14 of 19 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/powershell/auditpolicydsc/37#-LDGYQI79_Nn3pT5Yuqa:-LDGYQI79_Nn3pT5Yuqb:b-nphn2e) (no related file):*
Please update the appveyor.yml (to support Codecov) to the one in the template; https://github.com/PowerShell/DscResources/blob/master/DscResource.Template/appveyor.yml

It looks to me like you can replace it 1:1 (except for the version number).

---

*[a discussion](https://reviewable.io/reviews/powershell/auditpolicydsc/37#-LDGYu_o94gTmp5-75Q_:-LDGYu_o94gTmp5-75Qa:b-3ctpjt) (no related file):*
Suggest adding Codecov badges (or the entire Branches section here); https://github.com/PowerShell/SqlServerDsc#branches

---

*[AuditPolicyDsc.psd1, line 15 at r3](https://reviewable.io/reviews/powershell/auditpolicydsc/37#-LDGVhIE7UT-UJKsoEXb:-LDGVhIE7UT-UJKsoEXc:bxbu56k) ([raw file](https://github.com/powershell/auditpolicydsc/blob/edb807a25097b8b61e179d7aee14ceda1fd728a3/AuditPolicyDsc.psd1#L15)):*
> ```PowerShell
> 
> # Version number of this module.
> ModuleVersion = '1.1.1.0'
> ```

We should not change this. This is updated when releasing. 

---

*[DSCResources/MSFT_AuditPolicySubcategory/MSFT_AuditPolicySubcategory.psm1, line 140 at r3](https://reviewable.io/reviews/powershell/auditpolicydsc/37#-LDG_KMC-7ZcQ-UDx0TC:-LDG_KMC-7ZcQ-UDx0TD:bujcbjk) ([raw file](https://github.com/powershell/auditpolicydsc/blob/edb807a25097b8b61e179d7aee14ceda1fd728a3/DSCResources/MSFT_AuditPolicySubcategory/MSFT_AuditPolicySubcategory.psm1#L140)):*
> ```PowerShell
>         [ValidateSet('Present', 'Absent')]
>         [String]
>         $Ensure = 'Present'
> ```

Please add this change as an entry to the unreleased section.

---

*[Tests/Integration/AuditPolicyResourceHelper.Integration.Tests.ps1, line 48 at r3](https://reviewable.io/reviews/powershell/auditpolicydsc/37#-LDGXfFcA1KXqvKU2J1K:-LDGXfFcA1KXqvKU2J1L:bewzb09) ([raw file](https://github.com/powershell/auditpolicydsc/blob/edb807a25097b8b61e179d7aee14ceda1fd728a3/Tests/Integration/AuditPolicyResourceHelper.Integration.Tests.ps1#L48)):*
> ```
> $subcategories
> ```

Should this be `$script:subcategories`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/auditpolicydsc/37)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 107 at r3](https://reviewable.io/reviews/powershell/auditpolicydsc/37#-LDG_tg36k3Uu4v_Dzxb:-LDG_tg4-2rStZaiI0U6:b6zljia) ([raw file](https://github.com/powershell/auditpolicydsc/blob/edb807a25097b8b61e179d7aee14ceda1fd728a3/README.md#L107)):*
> ```Markdown
> ### Unreleased
> 
> Moved auditpol call to external process
> ```

Could we make this a bit more descriptive, for example why this was done? Also, maybe add that it now process the CSV output differently? I suggest we also add what resource(s) this change affect,

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/auditpolicydsc/37)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/auditpolicydsc/37)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/auditpolicydsc/37#-:-LDa65bu9t9m5uVvRTy6:bnfp4nl)*

**Comment by johlju** [comment]
@athaynes I let you merge this one as you are the maintainer for this resource module.

**Pull request merged**
